name: Sync DEPENDABOT to Jira
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  jira:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: Dependabot JIRA Action
        uses: Khairajani/dependabot-jira-action@add_to_issue
        with:
          jiraIssueLabel: dependabot
          jiraProjectKey: SCRUM
          jiraIssueType: Task
          githubRepo: code_scan
          githubOwner: Khairajani
        env:
          JIRA_SUBDOMAIN: 'khairajani'
          JIRA_USER_EMAIL: '${{ secrets.JIRA_EMAIL }}'
          JIRA_API_TOKEN: '${{ secrets.JIRA_TOKEN }}'
          GITHUB_API_TOKEN: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'